/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2019-10-29 01:22:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.roundback;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\thref=\"../jquery-easyui-1.7.0/themes/bf/easyui2.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\thref=\"../jquery-easyui-1.7.0/themes/icon.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\thref=\"../jquery-easyui-1.7.0/demo/demo.css\">\r\n");
      out.write("\t<script type=\"text/javascript\"\tsrc=\"../jquery-easyui-1.7.0/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\tsrc=\"../jquery-easyui-1.7.0/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\tsrc=\"../jquery-easyui-1.7.0/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>手环地图-轨迹回放</title>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/common.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"index.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"toBack()\">\r\n");
      out.write("\t<div class=\"easyui-layout\" style=\"width: 100%;height: 100%\">\r\n");
      out.write("\t\t<div data-options=\"region:'west',collapsible:false\" style=\"width:280px;height: 100%\">\r\n");
      out.write("\t\t\t<div class=\"easyui-tabs\" style=\"height: 100%\">\r\n");
      out.write("\t\t\t\t<div title=\"轨迹可视化\">\r\n");
      out.write("\t\t\t\t\t<iframe id=\"myBackListIframe\" src=\"ygt_index.html\" style=\"width:100%;height: 98%;overflow: auto\"></iframe>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div title=\"轨迹列表\">\r\n");
      out.write("\t\t\t\t\t<table id=\"personBackList\"></table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div data-options=\"region:'center'\">\r\n");
      out.write("\t\t\t<div class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("\t\t\t\t<div data-options=\"region:'north'\" style=\"padding-left:20px;padding-top:20px;height:50px;\">\r\n");
      out.write("\t\t\t\t\t<span id=\"headSpan\" style=\"float:right;font-size: 18px;color: yellow;\">当前回放嫌疑人：占山；手环号：1201234</span>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" style=\"float: left;margin-left: 10px;\" onclick=\"toBack()\">重新回放</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div data-options=\"region:'center'\">\r\n");
      out.write("\t\t\t\t\t<iframe id=\"myRoundBackIframe\" src=\"main.html\" style=\"width: 99%;height: 98%\"></iframe>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
